// Generated by https://quicktype.io

export interface IProducto {
    nif:         string;
    modelo:      string;
    precio:      number;
    fabricante:  string;
    ciudad:      string;
    descripcion: string;
}

// export interface IProducto: Cliente[];