// Generated by https://quicktype.io

export interface ICliente {
    dni:       string;
    nombre:    string;
    ciudad:    string;
    telefono:  number;
    
}

export interface ICategoria {
    id:        string;
    nombre:    string;
    
}

export interface IProveedor {
    dni:         string;
    nombre:      string;
    email:       string;
    telefono:    number;
    
}
export interface IProducto {
    id:             string;
    modelo:         string;
    precio:         number;
    fabricante:     string;
    imagen:         string;
    descripcion:    string;
    idCliente:      string;
    idCategoria:      string;
    idProveedor:      string;
    cliente: ICliente
    categoria: ICategoria
    proveedor: IProveedor
    
}

// export interface IProducto: Producto[];