// Generated by https://quicktype.io

export interface IProveedor {
    dni:         string;
    nombre:      string;
    email:       string;
    telefono:    number;
    
}

// export interface IProveedor: Proveedor[];
