// Generated by https://quicktype.io

export interface ICliente {
    dni:       string;
    nombre:    string;
    ciudad:    string;
    telefono:  number;
    
}

// export interface IClientes: Cliente[];