// Generated by https://quicktype.io

export interface IAuth {
    email:         string;
    password:      string;
    facebook:      string;
    github:        string;
    idCliente:     string;

}

// export interface IAuth: Auth[];