// Generated by https://quicktype.io

export interface ICliente {
    dni:       string;
    nombre:    string;
    ciudad:    string;
    telefono:  number;
    
}
export interface IAuth {
    idUser:        string;
    email:         string;
    password:      string;
    facebook:      string;
    github:        string;
    idCliente:     string;
    cliente: ICliente

}

// export interface IAuth: Auth[];