// Generated by https://quicktype.io

export interface ICliente {
    dni:       string;
    nombre:    string;
    ciudad:    string;
    telefono:  number;
    
}
export interface IAuth {
    id?:           string;
    email:         string;
    password:      string;
    isActive?:     boolean;
    token?:        string;
    fullName:      string;
    facebook?:     string;
    github?:       string;
    roles?:        string[]
   
}

// export interface IAuth: Auth[];